<a href="https://colab.research.google.com/github/TONYCHARLES-52151314/NTU_ML2021/blob/main/pytorch_tutorial/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd

**numpy2tensor**

In [ ]:
x = torch.tensor([1,2,3])
print(x)
print(x.dtype)

tensor([1, 2, 3])
torch.int64


In [ ]:
numpy_array = np.array([[1,2,3],[4,5,6]])
y = torch.from_numpy(numpy_array)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


**DataFrame 转换成 tensor**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/data.csv')

使用 .values 属性将数据从 DataFrame 提取到一个 NumPy 数组中，然后使用 torch.tensor() 将该数组转换为张量。

In [ ]:
all_values = df.values

In [ ]:
tensor_of_df = torch.tensor(all_values)
print(tensor_of_df)

tensor([[ 1.6000,  7.2200],
        [13.0900, 32.4100],
        [ 6.9700, 17.4700]], dtype=torch.float64)


**basic language**

In [ ]:
random = torch.rand(2, 3)

print("RANDOM TENSOR:\n\n", random)

RANDOM TENSOR:

 tensor([[0.6164, 0.6837, 0.3691],
        [0.4976, 0.2931, 0.8406]])


In [ ]:
range_tensor = torch.arange(0, 10, step=1)

print("ARANGE TENSOR:", range_tensor)

ARANGE TENSOR: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
range_tensor = torch.arange(0, 10, step=0.5)

print("ARANGE TENSOR:", range_tensor)

ARANGE TENSOR: tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])


In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])


**增加维度**

In [ ]:
print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)
print("-"*45)

# Add dimension
expanded = x.unsqueeze(0)  # Add dimension at index 0

print("\nTENSOR WITH ADDED DIMENSION AT INDEX 0:\n\n", expanded)
print("\nTENSOR SHAPE:", expanded.shape)

ORIGINAL TENSOR:

 tensor([[1, 2, 3],
        [4, 5, 6]])

TENSOR SHAPE: torch.Size([2, 3])
---------------------------------------------

TENSOR WITH ADDED DIMENSION AT INDEX 0:

 tensor([[[1, 2, 3],
         [4, 5, 6]]])

TENSOR SHAPE: torch.Size([1, 2, 3])


In [ ]:
squeezed = expanded.squeeze(0)
print(squeezed)
print(squeezed.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


**reshape和转置**

In [ ]:
reshaped = x.reshape(3,2)
print(reshaped)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
transposed = x.transpose(0,1)
print(transposed)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


**张量合并**

In [ ]:
tensor_a = torch.tensor([
    [1,2],
    [3,4]])
tensor_b = torch.tensor([
    [5,6],
    [7,8]])
tensor_c = torch.cat((tensor_a,tensor_b),dim=1)
print(tensor_c)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


**切片**

In [ ]:
x = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("ORIGINAL TENSOR:\n\n", x)
print("\nTENSOR SHAPE:", x.shape)

ORIGINAL TENSOR:

 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

TENSOR SHAPE: torch.Size([3, 4])


In [ ]:
single_element_tensor = x[1, 2] #6
print(single_element_tensor)
print(single_element_tensor.dtype)
value = single_element_tensor.item()
print(value)

tensor(7)
torch.int64
7


In [ ]:
second_row = x[1]
print(second_row)

tensor([5, 6, 7, 8])


In [ ]:
last_row = x[-1] #-1的魔术贴
print(last_row)

tensor([ 9, 10, 11, 12])


**切片 ：使用 [start:end:step] 表示法提取子张量**

In [ ]:
first_two_rows = x[0:2]
print(first_two_rows)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
last_two_columns = x[:,2:]
print(last_two_columns)

tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]])


In [ ]:
every_other_col = x[:, ::2]
print(every_other_col)

tensor([[ 1,  3],
        [ 5,  7],
        [ 9, 11]])


In [ ]:
combined = x[0:2, 2:]
print(combined)

tensor([[3, 4],
        [7, 8]])


**高级索引**

**掩码**

In [ ]:
print(x)
mask = x > 6
print(mask)
mask_applied = x[mask]
print(mask_applied)
print(mask_applied.dtype)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
tensor([ 7,  8,  9, 10, 11, 12])
torch.int64


**fancy索引**

In [ ]:
row_indices = torch.tensor([0,2])
col_indices = torch.tensor([1,3])
get_values = x[row_indices[:, None], col_indices]  #，None那里其实是增加了一维，广播机制

**计算相关**

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(a+b)

tensor([5, 7, 9])


In [ ]:
print(a*b)

tensor([ 4, 10, 18])


In [ ]:
dot_product = torch.matmul(a, b)
print(dot_product)

tensor(32)


In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1],
          [2],
          [3]])
print(a+b)
print((a+b).dtype)

tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])
torch.int64


逻辑运算

In [ ]:
temperatures = torch.tensor([20, 35, 19, 35, 42])
is_hot = temperatures > 30
is_cold = temperatures <= 20
print(is_hot)
print(is_cold)
print(is_cold.dtype)

tensor([False,  True, False,  True,  True])
tensor([ True, False,  True, False, False])
torch.bool


In [ ]:
is_morning = torch.tensor([True, False, False, True])
is_raining = torch.tensor([False, False, True, True])
morning_and_raining = is_morning & is_raining
morning_or_raining = is_morning | is_raining
print(morning_and_raining)
print(morning_or_raining)

tensor([False, False, False,  True])
tensor([ True, False,  True,  True])


数据统计

In [ ]:
data = torch.tensor([10.0, 20.0, 30.0, 40.0, 50.0])
print(data.mean())
print(data.std())

tensor(30.)
tensor(15.8114)


类型转换

In [ ]:
print(data.dtype)
data_int = data.int()
print(data_int.dtype)

torch.float32
torch.int32


实例练习        ---------todo----------